Lab5/Controllers/AuthentificationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lab5.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.IdentityModel.Tokens.Jwt;
    using System.Security.Claims;
    using Microsoft.IdentityModel.Tokens;
    using Kursach.Domain.Abstractions;
    using Kursach.Domain.Utilities;

    public class AuthentificationController : Controller
    {
        private IUserRepository _userRepository;

        public AuthentificationController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("jwtToken");
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Authenticate(string username, string password)
        {
            // Проверяем пользователя
            var user = _userRepository.GetByUsername(username, true).Result;
            if (user is null || !PasswordHelper.VerifyPassword(password, user.PasswordHash, user.PasswordSalt))
            {
                ViewData["ErrorMessage"] = "Неверное имя пользователя или пароль";
                return View("Login");
            }

            // Создаем список утверждений (claims)
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Username),
                new Claim(ClaimTypes.Role, user.Role)
            };

            // Создаем JWT токен
            var jwt = new JwtSecurityToken(
                issuer: AuthOptions.ISSUER,
                audience: AuthOptions.AUDIENCE,
                claims: claims,
                expires: DateTime.UtcNow.Add(TimeSpan.FromMinutes(60)),
                signingCredentials: new SigningCredentials(AuthOptions.GetSymmetricSecurityKey(), SecurityAlgorithms.HmacSha256));

            var encodedJwt = new JwtSecurityTokenHandler().WriteToken(jwt);

            HttpContext.Response.Cookies.Append("jwtToken", encodedJwt, new CookieOptions()
            {
                HttpOnly = true,
                SameSite = SameSiteMode.Strict,
                Secure = true
            });

            return RedirectToAction("Welcome");
        }

        public IActionResult Welcome()
        {
            return View();
        }

    }
}

Lab5/Controllers/RegistrationController.cs
using Kursach.Domain.Abstractions;
using Kursach.Application;
using Microsoft.AspNetCore.Mvc;
using Kursach.Application.Dtos;
using Kursach.Domain.Utilities;
using Kursach.Domain.Entities;

namespace Lab5.Controllers
{
    public class RegistrationController : Controller
    {
        private IUserRepository _userRepository;

        public RegistrationController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(UserForCreationDto user)
        {
            if(!ModelState.IsValid)
            {
                return View(user);
            }

            if(_userRepository.Get(false).Result.Any(u => u.Username == user.Username))
            {
                ModelState.AddModelError("Username", "Имя пользователя уже занято");
                return View(user);
            }

            var hashedPassword = PasswordHelper.HashPassword(user.Password);

            var newUser = new User()
            {
                Username = user.Username,
                PasswordHash = hashedPassword.hash,
                PasswordSalt = hashedPassword.salt,
                Role = "User",
                CreatedAt = DateTime.Now
            };

            await _userRepository.Create(newUser);
            await _userRepository.SaveChangesAsync();

            return RedirectToAction("SuccessRegistration");
        }

        public IActionResult SuccessRegistration()
        {
            return View();
        }
    }
}

Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab5</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(User.Identity?.IsAuthenticated == false){
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParkingSpaces" asp-action="Index">Парковочные места</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registration" asp-action="Index">Регистрация</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity?.IsAuthenticated == true && User.IsInRole("User"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Клиенты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Автомобили</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParkingSpaces" asp-action="Index">Парковочные места</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentification" asp-action="Logout">Выйти</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity?.IsAuthenticated == true && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Клиенты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Автомобили</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParkingSpaces" asp-action="Index">Парковочные места</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                            </li>
                        </ul>

                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentification" asp-action="Logout">Выйти</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab5
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>